name: CI/CD Main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Spring Boot Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-backend:latest -f restaurant/Dockerfile restaurant

      - name: Build Vue.js Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-frontend:latest -f frontend/Dockerfile frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-frontend:latest

      - name: Generate and Push Tag
        run: |
          TAG="v$(date +'%Y.%m.%d.%H%M%S')" 
          git tag $TAG
          git push origin $TAG
